name: Deploy to AWS EC2

on:
  push:
    branches:
      - master # Trigger deployment saat push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          # SSH Private Key di-hardcode di sini
          ssh-private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            ISI_PRIVATE_KEY_PEM_KAMU_DI_SINI
            MIIEpAIBAAKCAQEA75p... (dan seterusnya)
            -----END RSA PRIVATE KEY-----

      - name: Deploy to AWS EC2
        run: |
    
          ssh -o StrictHostKeyChecking=no ubuntu@54.252.156.109 << 'EOF'
            cd /var/www/ci-cd-test
            sudo git pull origin master
            
            sudo systemctl restart nginx
          EOF